### ISSUE TITLE
Wiki: Input voltage Range 9-12 V RMS?

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Line_trigger#5]
Looking through the wiki the input voltage range does not specify what the 9-12 V input range refers to. Is this RMS, amplitude, or peak to peak? It would be nice to clarify this.

**Comment by gkasprow** [comment]
in the case of AC, we usually specify the RMS value.

**Comment by pathfinder49** [comment]
Thanks :) I've just set up one of these in the lab and would like to add a couple of things to the wiki. If you'd like to give me editing rights, I'll add this while I'm at it.

**Comment by gkasprow** [comment]
done

**Comment by pathfinder49** [comment]
Thanks Greg :) However, the editing rights don't seem to have worked. I still can't edit the Line_trigger wiki.

**Comment by gkasprow** [comment]
oh, I gave rights to the wrong pathfinder :)
